import { validateQuiz, validateRound, validateQuestion } from '@/lib/quiz/validate.js'

const autoFixers = {
  setUuid: (o, key, id) => { o[key] = uuidv4(); },
  setFullName: (o, key, id) => { o.fullName = `${o.name} - ${o.number}`}
}

const testQuiz = getQuiz();
const testRound = testQuiz.rounds[0];
const testQuestion = testRound.questions[0];

const vqz = validateQuiz(testQuiz);
console.log(vqz.isValid(), '===')

// const vqn = validateQuestion(testQuestion, 'R1Q1');
// console.log(vqn.getResult())
// const vrd = validateRound(testRound, 'R1');
// console.log(vrd.getResult())



/***************************************************************************/




function getQuiz() {
  return {
    "rounds": [
      {
        "name": "Ronde 1",
        "type": "normal",
        "theme": null,
        "roundNumber": 1,
        "binRootFolderId": "1AlE9aLZ2Xoc10mRIijE5kdIjub0N8Drh",
        "roundBinFolderId": "1xoIP6MArTf0ZPmF91EfPoIIl8zTX4VuV",
        "roundBinFolderPath": "QUIZ-250017 - ANWB - Kerst/Ronde 1",
        "uuid": "ed2de750-6db1-4e5a-b0cf-fae27f02da75",
        "questions": [
          {
            "nr": 1,
            "text-nl": "Welke kersthit hoor je hier? Artiest en Titel",
            "answer-nl": " Mariah Carey - All I Want For Christmas Is You",
            "difficulty": 1,
            "category": "music",
            "tags": "xmas",
            "media-type": "audio",
            "fullscreen": "",
            "media": "Mariah Carey - All I Want For Christmas Is You.mp3",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 2,
            "text-nl": "Welke stelling over Sinterklaas is waar? A) hij is geboren op 5 december B) hij is overleden op 5 december C) hij is geboren op 6 december D) hij is overleden op 6 december",
            "answer-nl": "D) hij is overleden op 6 december",
            "difficulty": 2,
            "category": "history",
            "tags": "xmas",
            "media-type": "image",
            "fullscreen": "",
            "media": "St. Nicolaas.jpg",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 3,
            "text-nl": "Welke filmrol is gespeeld door Christian Bale, George Clooney, Val Kilmer en Michael Keaton?",
            "answer-nl": "Batman",
            "difficulty": 2,
            "category": "film & tv",
            "tags": "",
            "media-type": "image",
            "fullscreen": "",
            "media": "Batmen.jpg",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 4,
            "text-nl": "De naam van welke Amerikaanse stad betekent letterlijk \"De weiden\"?",
            "answer-nl": "Las Vegas",
            "difficulty": 3,
            "category": "geography",
            "tags": "",
            "media-type": "image",
            "fullscreen": "",
            "media": "Mown-path-meadow-1000x563.jpg",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 5,
            "text-nl": "Uit welk museum werd in januari 2025 deze helm gestolen?",
            "answer-nl": "Drents Museum",
            "difficulty": 2,
            "category": "art & literature",
            "tags": 2025,
            "media-type": "image",
            "fullscreen": "",
            "media": "330px-Helmet_of_Cotofenesti_-_Front_Large_by_Radu_Oltean.jpg",
            "media-path": "QUIZ-250016 - Mets 3.4/Ronde 1",
            "media-id": "1honxhojt9_NtRRtRaD2z5zt0xR4wkJpH",
            "uuid": "18a2a85f-4e1d-4d3e-be19-2bcdf6b810fc",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 6,
            "text-nl": "Welk rendier is genoemd naar het Engelse woord voor 'rekel'?",
            "answer-nl": "Vixen",
            "difficulty": 3,
            "category": "general",
            "tags": "xmas",
            "media-type": "image",
            "fullscreen": "",
            "media": "fox.jpg",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 7,
            "text-nl": "Hoe wordt de maandag na 'Black Friday' genoemd?",
            "answer-nl": "Cyber Monday",
            "difficulty": 2,
            "category": "general",
            "tags": "xmas",
            "media-type": "image",
            "fullscreen": true,
            "media": "UPS-Amazon.jpg",
            "media-path": "QUIZ-250017 - ANWB - Kerst/Ronde 1",
            "media-id": "19GcOfhvMQ3QzrX7G6Ep-jOuLhixmCB_x",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 8,
            "text-nl": "Wie riep 'Eureka' nadat hij in een bad was gaan zitten?",
            "answer-nl": "Archimedes",
            "difficulty": 1,
            "category": "science",
            "tags": "",
            "media-type": "image",
            "fullscreen": "",
            "media": "eureka.jpg",
            "media-path": "QUIZ-250016 - Mets 3.4/Ronde 5",
            "media-id": "1i5BWE6V2HXBzyMwxB1nplQe90i8oZKU1",
            "uuid": "d2500b40-4cf5-4313-9a01-29cdaf58005f",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 9,
            "text-nl": "In welk jaar werd de eerste elektrische auto geproduceerd? Je mag er 10 jaar naast zitten.",
            "answer-nl": 1881,
            "difficulty": 3,
            "category": "general",
            "tags": "anwb",
            "media-type": "image",
            "fullscreen": "",
            "media": "unplug-and-hang-on-five-interesting-vintage-electric-cars-1476934604659.webp",
            "media-path": "QUIZ-250017 - ANWB - Kerst/Ronde 1",
            "media-id": "12NyoaMBqC0mNcJC0nMrBNP03SL84zx9K",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 10,
            "text-nl": "Welke kersthit hoor je hier? Artiest en Titel.",
            "answer-nl": "Brenda Lee - Rockin' Around The Christmas Tree",
            "difficulty": 3,
            "category": "music",
            "tags": "xmas",
            "media-type": "audio",
            "fullscreen": "",
            "media": "Brenda Lee - Rockin' Around The Christmas Tree.mp3",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          }
        ]
      },
      {
        "name": "Ronde 2",
        "type": "normal",
        "theme": null,
        "roundNumber": 2,
        "binRootFolderId": "1AlE9aLZ2Xoc10mRIijE5kdIjub0N8Drh",
        "roundBinFolderId": "1rLqbvOWcoYoCNoTMTvL8SOnOjME6RKXR",
        "roundBinFolderPath": "QUIZ-250017 - ANWB - Kerst/Ronde 2",
        "uuid": "6a584db8-e425-4bf6-9bb3-654c578bc7dc",
        "questions": [
          {
            "nr": 1,
            "text-nl": "Wat gebeurde op 3 september 1967 in Zweden, op 2 april 1974 in Nigeria en op 4 augustus 1974 in Ghana, maar precies tegenovergesteld op 1 september 2009 in Samoa?",
            "answer-nl": "Het wegverkeer ging van links- naar rechtsrijdend.",
            "difficulty": 2,
            "category": "general",
            "tags": "",
            "media-type": "image",
            "fullscreen": "",
            "media": "7b8b4b77-01a0-46a7-b6f4-fb67a34b26e9.jpg",
            "media-path": "QUIZ-250014 - Mets 3.2/Ronde 5",
            "media-id": "1BGpHIPXZbA5o3E1odaJafLcwkAqJRA9I",
            "uuid": "ce45aece-82e8-45a9-aac2-05ecb7d0ba1f",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 2,
            "text-nl": "Overleden met Kerst: in welk jaar stond, volgens het liedje, Flappie op het menu?",
            "answer-nl": 1961,
            "difficulty": 2,
            "category": "general",
            "tags": "xmas",
            "media-type": "image",
            "fullscreen": "",
            "media": "konijntje.jpg",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 3,
            "text-nl": "Wie is naast Caspar en Balthazar de derde wijze die Jezus bezocht?",
            "answer-nl": "Melchior",
            "difficulty": 2,
            "category": "general",
            "tags": "xmas",
            "media-type": "video",
            "fullscreen": "",
            "media": "Kroamschud'n 3 kluge Leute Mariaparochie 3 kluge Leute.mp4",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 4,
            "text-nl": "Afgelopen maart werd Kirsty Coventry gekozen tot de eerste vrouwelijke voorzitter van het IOC. Uit welk land komt zij?",
            "answer-nl": "Zimbabwe",
            "difficulty": 3,
            "category": "sports",
            "tags": 2025,
            "media-type": "image",
            "fullscreen": "",
            "media": "250320-Kirsty-Coventry-vl-1257p-3225cc.webp",
            "media-path": "QUIZ-250016 - Mets 3.4/Ronde 2",
            "media-id": "1us7ZCH5xafXs90BFot6-AvXgIG97B5oX",
            "uuid": "995fa7e0-43fb-4aa4-a323-a939e96ede77",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 5,
            "text-nl": "Welke monnik wordt, niet volledig terecht, vaak beschouwd als de uitvinder van de champagne?",
            "answer-nl": "Dom Perignon",
            "difficulty": 2,
            "category": "general",
            "tags": "",
            "media-type": "image",
            "fullscreen": true,
            "media": "champagne_0.jpg",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 6,
            "text-nl": "Van welk gerenommeerd modehuis is Duran Lantink (Den Haag, 1987) sinds april 2025 creatief directeur?",
            "answer-nl": "Jean-Paul Gaultier",
            "difficulty": 3,
            "category": "general",
            "tags": 2025,
            "media-type": "image",
            "fullscreen": "",
            "media": "duran-lantink.jpg",
            "media-path": "QUIZ-250017 - ANWB - Kerst/Ronde 2",
            "media-id": "1NFOWrAGZdWtqpEgzHgEhjsJW8rj0z4HY",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 7,
            "text-nl": "Welk land zie je hier?",
            "answer-nl": "China",
            "difficulty": 1,
            "category": "geography",
            "tags": "",
            "media-type": "image",
            "fullscreen": "",
            "media": "ChinaGold.png",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 8,
            "text-nl": "Welke sitcom zie je hier?",
            "answer-nl": "Modern Family",
            "difficulty": 1,
            "category": "film & tv",
            "tags": "",
            "media-type": "video",
            "fullscreen": "",
            "media": "Modern Family leader.mp4",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 9,
            "text-nl": "Heike Kamerlingh-Onnes was de eerste die erin slaagde helium vloeibaar te maken. Hiermee was tussen 1908 en 1923 zijn laboratorium de koudste plek op aarde. In welke stad was dit?",
            "answer-nl": "Leiden",
            "difficulty": 2,
            "category": "science",
            "tags": "",
            "media-type": "image",
            "fullscreen": "",
            "media": "70678192_10156688220789103_7973339401834987520_n.jpg",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 10,
            "text-nl": "Welke kersthit hoor je hier? Artiest en titel.",
            "answer-nl": "Kelly Clarkson - Underneath the tree",
            "difficulty": 2,
            "category": "music",
            "tags": "xmas",
            "media-type": "audio",
            "fullscreen": "",
            "media": "Kelly Clarkson Underneath the Tree Audio (mp3cut.net).mp3",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          }
        ]
      },
      {
        "name": "Ronde 3",
        "type": "normal",
        "theme": null,
        "roundNumber": 3,
        "binRootFolderId": "1AlE9aLZ2Xoc10mRIijE5kdIjub0N8Drh",
        "roundBinFolderId": "1WF9nW0OXWrDN16eAVIGZaepOgD2ccg8R",
        "roundBinFolderPath": "QUIZ-250017 - ANWB - Kerst/Ronde 3",
        "uuid": "274fb559-a64e-47e1-b56c-a7efb5352bff",
        "questions": [
          {
            "nr": 1,
            "text-nl": "Ze werd geboren als prinses Sophie van Anhalt-Zerbst, en regeerde tussen 1762 en 1796. Onder welke naam kennen wij haar beter?",
            "answer-nl": "Catharina de Grote",
            "difficulty": 3,
            "category": "history",
            "tags": "",
            "media-type": "image",
            "fullscreen": "",
            "media": "Catherine_II_by_A.Albertrandi_after_Rokotov.jpg",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 2,
            "text-nl": "Welke nummer hoor je hier? Artiest en titel.",
            "answer-nl": "Taylor Swift - The Faith of Ophelia",
            "difficulty": 2,
            "category": "music",
            "tags": "",
            "media-type": "audio",
            "fullscreen": "",
            "media": "Taylor Swift - The Fate of Ophelia (Official Music Video) [ko70cExuzZM] (mp3cut.net).mp3",
            "media-path": "QUIZ-250017 - ANWB - Kerst/Ronde 3",
            "media-id": "17u0divmVeRIAI5e3aeufEPn2m3vQdFI5",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 3,
            "text-nl": "Welke renner werd na Pogacar en Vingegaard derde in de Tour van 2025?",
            "answer-nl": "Florian Lipowitz",
            "difficulty": 3,
            "category": "sports",
            "tags": 2025,
            "media-type": "image",
            "fullscreen": true,
            "media": "image-203c53d6-9e96-4c01-9242-d114b72c8eb9-85-2560-1440.jpg",
            "media-path": "QUIZ-250016 - Mets 3.4/Ronde 4",
            "media-id": "16lFoyXGzyX6GcKkScBwxAnQaTMhiPDhs",
            "uuid": "617abd7e-f4d4-4188-ad4a-815db9bcc2f1",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 4,
            "text-nl": "Van wie zijn de woorden ‘Zoo ik iéts ben, ben ik een Hagenaar’?",
            "answer-nl": "Louis Couperus",
            "difficulty": 1,
            "category": "art & literature",
            "tags": "",
            "media-type": "image",
            "fullscreen": "",
            "media": "couperus-door-donkersloot.jpg",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 5,
            "text-nl": "Met drie Olympische, drie Wereld- en twee Europese titels is ze de meest succesvolle zevenkampster ooit. Wie is deze Belgische?",
            "answer-nl": "Nafi Thiam",
            "difficulty": 2,
            "category": "sports",
            "tags": "",
            "media-type": "image",
            "fullscreen": "",
            "media": "NafiThiam.jpg",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 6,
            "text-nl": "Wie zijn dit?",
            "answer-nl": "Jeroen Woe, Niels van der Laan, Miguel Wiels",
            "difficulty": 2,
            "category": "film & tv",
            "tags": "",
            "media-type": "image",
            "fullscreen": "",
            "media": "jeroenwoenielsvanderlaanterugkeermiguelwielsnieuwseizoentv.webp",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 7,
            "text-nl": "Rosalind Franklin was samen met James Watson en Francis Crick (die hiervoor wél een Nobelprijs ontvingen) verantwoordelijk voor de ontdekking van de structuur van welk molecuul?",
            "answer-nl": "DNA",
            "difficulty": 3,
            "category": "science",
            "tags": "",
            "media-type": "image",
            "fullscreen": "",
            "media": "Rosalind-Franklin_1.webp",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 8,
            "text-nl": "Welke engel kwam de Blijde Boodschap aan Maria brengen over de komst van het kindeke Jezus?",
            "answer-nl": "Gabriël (Lucas 1:26-38)",
            "difficulty": 2,
            "category": "general",
            "tags": "xmas",
            "media-type": "image",
            "fullscreen": "",
            "media": "Gabriel Y Maria.jpg",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 9,
            "text-nl": "Dit jaar zijn onder meer Exlantix, Firefly en Jaecoo op de Nederlandse markt verschenen. Wat zijn het?",
            "answer-nl": "Chinese automerken",
            "difficulty": 2,
            "category": "general",
            "tags": 2025,
            "media-type": "image",
            "fullscreen": "",
            "media": "3_16x9.avif",
            "media-path": "QUIZ-250016 - Mets 3.4/Ronde 5",
            "media-id": "1GItgDtuILwGUGAWq9voWWQDTWf_haiCn",
            "uuid": "ab70b809-de22-451e-a77a-5a33386bb527",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 10,
            "text-nl": "Welke kersthit hoor je hier? Artiest en titel.",
            "answer-nl": "Shakin' Stevens - Merry Christmas Everyone",
            "difficulty": 2,
            "category": "music",
            "tags": "xmas",
            "media-type": "audio",
            "fullscreen": "",
            "media": "XM - Shakin' Stevens - Merry Christmas Everyone.mp3",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          }
        ]
      },
      {
        "name": "Ronde 4",
        "type": "normal",
        "theme": null,
        "roundNumber": 4,
        "binRootFolderId": "1AlE9aLZ2Xoc10mRIijE5kdIjub0N8Drh",
        "roundBinFolderId": "1rcf1g380SVDZpolFqFcH9fxho8sV30qr",
        "roundBinFolderPath": "QUIZ-250017 - ANWB - Kerst/Ronde 4",
        "uuid": "5ed841cd-4db7-4a97-9bb4-dd04d4cf0bb4",
        "questions": [
          {
            "nr": 1,
            "text-nl": "Wat is het Latijnse woord voor 'driesprong'?",
            "answer-nl": "Trivia",
            "difficulty": 2,
            "category": "general",
            "tags": "",
            "media-type": "image",
            "fullscreen": "",
            "media": "DRIEPRONG.jpg",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 2,
            "text-nl": "Haagser dan dit kan bijna niet. Welke tiepetjes van Van Kooten en De Bie horen we hier?",
            "answer-nl": "De Klisjeemannetjes",
            "difficulty": 2,
            "category": "film & tv",
            "tags": "",
            "media-type": "audio",
            "fullscreen": "",
            "media": "De Klisjeemannetjes (mp3cut.net)-2.mp3",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 3,
            "text-nl": "Op 1 september 2025 nam ze na 37 jaar afscheid als hoofdredactrice van Vogue. Wat is haar naam?",
            "answer-nl": "Anna Wintour",
            "difficulty": 2,
            "category": "art & literature",
            "tags": 2025,
            "media-type": "image",
            "fullscreen": "",
            "media": "npr.brightspotcdn.jpg",
            "media-path": "QUIZ-250016 - Mets 3.4/Ronde 6",
            "media-id": "1LrkoD0D9AAT_CcutmsiCdgqr1p5vLhVk",
            "uuid": "7b81a8e5-f9fa-4ecc-a6c3-063d6f91d5c7",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 4,
            "text-nl": "Met welk muziekstuk wordt het Nieuwjaarsconcert in Wenen traditioneel afgesloten?",
            "answer-nl": "Radetzki-mars",
            "difficulty": 2,
            "category": "music",
            "tags": "xmas",
            "media-type": "image",
            "fullscreen": "",
            "media": "ORF-Ali-Schafler.jpg",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 5,
            "text-nl": "Hoe wordt het Kerstfeest in de Scandinavische landen genoemd?",
            "answer-nl": "Jul",
            "difficulty": 3,
            "category": "general",
            "tags": "xmas",
            "media-type": "image",
            "fullscreen": true,
            "media": "jul_Stockholm_view_christmas_tree_Photo_Henri.width-1440.jpg",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 6,
            "text-nl": "Welke likeur wordt gebruikt bij de bereiding van het nagerecht Crêpes Suzette, dat over enkele dagen weer menige kerstdis zal afsluiten?",
            "answer-nl": "Grand Marnier, Cointreau, Triple Sec of Curaçao",
            "difficulty": 1,
            "category": "general",
            "tags": "xmas",
            "media-type": "image",
            "fullscreen": "",
            "media": "Crepes Suzette.jpg",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 7,
            "text-nl": "Welke schaatsster won drie gouden medailles op de Olympische Spelen van Calgary in 1988?",
            "answer-nl": "Yvonne van Gennip",
            "difficulty": 2,
            "category": "sports",
            "tags": "",
            "media-type": "image",
            "fullscreen": "",
            "media": "yvonne-van-gennip-3km-calgary-met-ehrig-en-zange.jpg",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 8,
            "text-nl": "Wat is de Nederlandse benaming van de mistletoe?",
            "answer-nl": "Maretak",
            "difficulty": 1,
            "category": "science",
            "tags": "xmas",
            "media-type": "image",
            "fullscreen": true,
            "media": "mistletoe.jpg",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 9,
            "text-nl": "In mei werd de Amerikaan Robert Francis Prevost gekozen tot paus. Hij werd hiermee de eerste niet-europese paus sinds de Syriër Gregorius III. In welke eeuw was dat? Je mag er een eeuw naastzitten.",
            "answer-nl": "8ste eeuw (731 - 741)",
            "difficulty": 3,
            "category": "history",
            "tags": 2025,
            "media-type": "image",
            "fullscreen": "",
            "media": "178-7866_IMG_-_Gregorius_III_AV.png",
            "media-path": "QUIZ-250016 - Mets 3.4/Ronde 3",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 10,
            "text-nl": "Artiest - Titel",
            "answer-nl": "Merol - Kerst met de Fam",
            "difficulty": 2,
            "category": "music",
            "tags": "xmas",
            "media-type": "video",
            "fullscreen": "",
            "media": "Merol - Kerst met de Fam, kort.mp4",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          }
        ]
      },
      {
        "name": "Ronde 5",
        "type": "normal",
        "theme": null,
        "roundNumber": 5,
        "binRootFolderId": "1AlE9aLZ2Xoc10mRIijE5kdIjub0N8Drh",
        "roundBinFolderId": "14yLvzMi_1Mz9Re6dYKys44eVMix5HAXO",
        "roundBinFolderPath": "QUIZ-250017 - ANWB - Kerst/Ronde 5",
        "uuid": "64135f55-4d84-4acd-a526-81282d76767d",
        "questions": [
          {
            "nr": 1,
            "text-nl": "Deze man werd in februari 2025 premier van België. Wat is zijn naam?",
            "answer-nl": "Bart de Wever",
            "difficulty": 3,
            "category": "general",
            "tags": 2025,
            "media-type": "image",
            "fullscreen": "",
            "media": "BartDeWever.jpg",
            "media-path": "QUIZ-250016 - Mets 3.4/Ronde 1",
            "media-id": "1DEF7JnjwIb1__lG1ntwvlp0TE6JfwdBn",
            "uuid": "4ad9e633-0f0c-4b5d-a3e2-7860e59bcb9f",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 2,
            "text-nl": "Van welke artiest zie je hier een zelfportret?",
            "answer-nl": "Frida Kahlo",
            "difficulty": 2,
            "category": "art & literature",
            "tags": "",
            "media-type": "image",
            "fullscreen": "",
            "media": "frida-kahlo-self-portrait-640-full.jpg",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 3,
            "text-nl": "Hoe wordt de zegening voor Rome en de wereld genoemd, die iedere Kerst door de Paus wordt uitgesproken?",
            "answer-nl": "Urbi et orbi",
            "difficulty": 1,
            "category": "general",
            "tags": "xmas",
            "media-type": "image",
            "fullscreen": "",
            "media": "Urbi-et-Orbi-Kerstmis-2021-paus-Franciscus-CNS-Vatican-Media.jpg",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 4,
            "text-nl": "Welke sport wordt met deze bal gespeeld?",
            "answer-nl": "Cricket",
            "difficulty": 2,
            "category": "sports",
            "tags": "",
            "media-type": "image",
            "fullscreen": "",
            "media": "Cricket_ball_on_grass.jpg",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 5,
            "text-nl": "In welk jaar was de slag bij Waterloo? Je mag er vijf jaar naastzitten, bonuspunt voor het juiste jaar.",
            "answer-nl": 1815,
            "difficulty": 2,
            "category": "history",
            "tags": "",
            "media-type": "image",
            "fullscreen": true,
            "media": "M-Waterloo-9-4C-Feb12-crop.jpg",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 6,
            "text-nl": "Welk land is de grootste exporteur van kerstbomen?",
            "answer-nl": "Canada",
            "difficulty": 1,
            "category": "general",
            "tags": "xmas",
            "media-type": "image",
            "fullscreen": "",
            "media": "kerststadje-canada.jpg",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 7,
            "text-nl": "Wie is de ontwerper van deze pumps? Voor een schamele 575 euro zijn ze van jou.",
            "answer-nl": "Christian Louboutin",
            "difficulty": 1,
            "category": "general",
            "tags": "",
            "media-type": "image",
            "fullscreen": "",
            "media": "Louboutins.jpg",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 8,
            "text-nl": "In welke Amerikaanse stad is het hoofdkwartier van Coca-Cola gevestigd?",
            "answer-nl": "Atlanta",
            "difficulty": 2,
            "category": "general",
            "tags": "xmas",
            "media-type": "image",
            "fullscreen": true,
            "media": "Cola truck kerst.jpg",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 9,
            "text-nl": "Drie auto-modellen worden erkent als zijnde 'best verkochte modellen ter wereld' (bron: Wikipedia). Welke drie zijn dit?",
            "answer-nl": "Ford Model T, Volkswagen Kever, Toyota Corolla",
            "difficulty": 2,
            "category": "general",
            "tags": "anwb",
            "media-type": "image",
            "fullscreen": "",
            "media": "Parking_lot_at_HAA_Kobe-1000x625.jpg",
            "media-path": "QUIZ-250017 - ANWB - Kerst/Ronde 5",
            "media-id": "1d3cFp4pn1blD5tGWyrYHsrW1P5OmdAmQ",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 10,
            "text-nl": "Welke kersthit hoor je hier? Artiest en titel.",
            "answer-nl": "Bing Crosby - White Christmas",
            "difficulty": 1,
            "category": "music",
            "tags": "xmas",
            "media-type": "audio",
            "fullscreen": "",
            "media": "XM - Bing Crosby - White Christmas.mp3",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          }
        ]
      },
      {
        "name": "Ronde 6",
        "type": "normal",
        "theme": null,
        "roundNumber": 6,
        "binRootFolderId": "1AlE9aLZ2Xoc10mRIijE5kdIjub0N8Drh",
        "roundBinFolderId": "12xW1up1XVvizG5oDNFtWjmd3-5sE5YbM",
        "roundBinFolderPath": "QUIZ-250017 - ANWB - Kerst/Ronde 6",
        "uuid": "dabe8c1e-9374-4385-95b8-8ef555471440",
        "questions": [
          {
            "nr": 1,
            "text-nl": "Hoe heet de vrekkige hoofdpersoon uit Charles Dickens' \"A Christmas Carol\"?",
            "answer-nl": "Scrooge",
            "difficulty": 1,
            "category": "art & literature",
            "tags": "xmas",
            "media-type": "image",
            "fullscreen": true,
            "media": "Carol-l_8BEDaF6-1.jpg",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 2,
            "text-nl": "Welke kersthit hoor je hier? Artiest en titel.",
            "answer-nl": "Bianca Ryan - Why Couldn't It Be Christmas Every Day",
            "difficulty": 3,
            "category": "music",
            "tags": "xmas",
            "media-type": "audio",
            "fullscreen": "",
            "media": "XM - Bianca Ryan - Why Couldn't It Be Christmas Every Day.mp3",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 3,
            "text-nl": "In welk jaar is de ANWB opgericht? Je mag er vijf jaar naast zitten.",
            "answer-nl": 1883,
            "difficulty": 3,
            "category": "general",
            "tags": "",
            "media-type": "image",
            "fullscreen": "",
            "media": "ANWB_schildje.jpg",
            "media-path": "QUIZ-250017 - ANWB - Kerst/Ronde 6",
            "media-id": "1g7vu0LXsxp-3xyr9WHaR8oD0JDa5DKNK",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 4,
            "text-nl": "Deze regisseur won twee beste regie-Oscars. Noem beide films.",
            "answer-nl": "Schindler's List, Saving Private Ryan",
            "difficulty": 2,
            "category": "film & tv",
            "tags": "",
            "media-type": "image",
            "fullscreen": "",
            "media": "MV5BMTY1NjAzNzE1MV5BMl5BanBnXkFtZTYwNTk0ODc0._V1_FMjpg_UX1000_.jpg",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 5,
            "text-nl": "Wie werd in oktober 2025 met 248 interlands record-international van Oranje?",
            "answer-nl": "Sharida Spitse",
            "difficulty": 2,
            "category": "sports",
            "tags": 2025,
            "media-type": "image",
            "fullscreen": true,
            "media": "oranje_32.jpg",
            "media-path": "QUIZ-250016 - Mets 3.4/Ronde 7",
            "media-id": "1ZkweHGLd2TUfDlB0pqPtA-SeiWq0XOvl",
            "uuid": "e523b0fb-3fdb-451c-bfa7-7e8b32aebb33",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 6,
            "text-nl": "Hier zie je Margaret Hamilton. Ze staat naast de computercode die onder haar leiding geschreven werd om in 1969 mensen naar de maan en weer terug te brengen. Wat is de naam van het maanlandings-project?",
            "answer-nl": "Apollo",
            "difficulty": 1,
            "category": "history",
            "tags": "",
            "media-type": "image",
            "fullscreen": "",
            "media": "margaret_hamilton_-_restoration.webp",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 7,
            "text-nl": "Welk Europees bedrijf is in aantallen geproduceerde banden de grootste ter wereld?",
            "answer-nl": "Lego",
            "difficulty": 3,
            "category": "general",
            "tags": "anwb",
            "media-type": "image",
            "fullscreen": true,
            "media": "used-tyres-high-quality-1-3.jpg",
            "media-path": "QUIZ-250016 - Mets 3.4/Ronde 7",
            "media-id": "13-FEewdDPdaJurzoRDTqmGjRENWuaN0s",
            "uuid": "ef1edfc8-e332-4cdc-8ba9-07d1bb7dd961",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 8,
            "text-nl": "Wie is de verteller in de verhalen van 1001 nacht?",
            "answer-nl": "Sheherazade",
            "difficulty": 1,
            "category": "art & literature",
            "tags": "",
            "media-type": "image",
            "fullscreen": "",
            "media": "Scheherazade-from-A-Thousand-and-One-Nights-1911-illustration-by-Edmund-Dulac.webp",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 9,
            "text-nl": "Lengtegraden zijn denkbeeldige lijnen die haaks op de evenaar staan. Wat is het andere woord voor lengtegraden?",
            "answer-nl": "Meridianen",
            "difficulty": 2,
            "category": "geography",
            "tags": "",
            "media-type": "image",
            "fullscreen": "",
            "media": "wereldkaart-met-parallel-en-meridiaan.jpg",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          },
          {
            "nr": 10,
            "text-nl": "Welke kersthit hoor je hier? Artiest en titel.",
            "answer-nl": "Slade - Merry Xmas Everybody",
            "difficulty": 1,
            "category": "music",
            "tags": "xmas",
            "media-type": "audio",
            "fullscreen": "",
            "media": "Slade - Merry Xmas Everybody cut.mp3",
            "media-path": "",
            "media-id": "",
            "uuid": "",
            "source": "",
            "type": "normal"
          }
        ]
      }
    ],
    "name": "ANWB - Kerst",
    "number": "QUIZ-250017",
    "fullName": "QUIZ-250017 - ANWB - Kerst",
    "uuid": "fba5ef53-704f-4725-948c-e08fe09e09af",
    "meta": {
      "template": "4.0",
      "uuid": "bc2ea8e6-ccc4-401f-992e-0c72470bace3",
      "number": "QUIZ-250017",
      "name": "ANWB - Kerst",
      "date": "4-12-2025",
      "format": "normal*6",
      "binRootFolderPath": "container/bin",
      "audience": "anwb",
      "jsonFolderPath": "container/quiz/json"
    }
  }
}